### ISSUE TITLE
Bug with `DISABLED_FEATURE` option

### ISSUE THREAD

**Issue by guits** [pastefile/pastefile#9]
1d8ff2a introduced a bug with the `DISABLED_FEATURE` option :

[`os.environ.get()`](https://github.com/pastefile/pastefile/blob/dev/pastefile/app.py#L35) return an `str` and won't convert it into a list.

Therefore, if for any reason I set DISABLED_FEATURE as following :

`DISABLED_FEATURE: ['pattern_ls_pattern']` 

the code will enter in this condition while it shouldn't :

[`if 'ls' in app.config['DISABLED_FEATURE']:`](https://github.com/pastefile/pastefile/blob/dev/pastefile/app.py#L140)

The easiest way to fix it would be probably to use a comma separated list instead of json array for this parameters.

**Comment by gaelL** [comment]
This issue is also for `DISPLAY_FOR`
